### ISSUE TITLE
New Taxon Check var from NL

### ISSUE THREAD

**Issue by herbier** [irbv-collections/MT-controlled-vocabulary#1621]
[Originally posted on GoogleCode (id 1319) on 2014-10-03 by dianepelley]

<b>(This is the template to report a new taxon. For another issue, change the</b>
<b>template above.)</b>
<b>1. Report the new scientific name you found on the specimen label below.</b>
2. Enter &quot;pending&quot; as a temporary scientific name.
<b>3. The collection staff will verify the name and add it to the database.</b>
<b>4. You will receive a confirmation by email.</b>

<b>Scientific name:</b>

Det 1 = Eupatorium maculatum var. foliosum (Ernest Rouleau)
Det 2 = Eupatorium maculatum var. foliosum (Stuart Hay)
Det 3 = Eutrochium maculatum (Luc Brouillet - electronic)

var. foliosum excluded from Vascan
http://data.canadensys.net/vascan/taxon/3164

ID of the specimen(s): 89404

Your name: Diane Pelley

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-03 17:23Z]

The name is not excluded - it is now a synonym

In the MT database entry 89404, I was careful not to automatically enter the var. in my electronic ann. because I wanted the var. to be validated

The names are in the Taxon database already

I am not sure what you are requesting

LB
